package fr.irit.smac.amasrenderer.view;

public class StyleSheet {
    
    public static final String styleSheet_Stupid = 
        "graph {"
            + "fill-image: url('C:/Users/Utilisateur/Desktop/jpeg_meme/zoidberg splash.jpg');"
            + "fill-mode: image-scaled-ratio-max;"
        + "}"
        + "node {"
            +"shape: circle;"
            +"size: 50px;"
            +"fill-image: url('C:/Users/Utilisateur/Desktop/jpeg_meme/DAFUUQ.jpg');"
            +"fill-mode: image-scaled-ratio-max;"
            +"text-mode: hidden;"
            +"z-index: 0;"
        +"}"
        + "edge {"
            + "shape: line;"
            + "fill-color: #222;"
            + "arrow-size: 6px, 4px;"
            + "z-index: 0;"
        + "}"
        + "node:clicked {"
            + "fill-color: red;"
        + "}"
        + "node:selected {"
            +"shape: circle;"
            +"size: 25px;"
            +"fill-image: url('C:/Users/Utilisateur/Desktop/jpeg_meme/Psycho.jpg');"
            +"fill-mode: image-scaled-ratio-max;"
            +"text-mode: hidden;"
            +"z-index: 0;"
        + "}"
        + "edge.selection {"
            + "fill-color: red;"
        + "}";
    
    public static final String styleSheet1 = 
        "node {"
            + "size: 6px;"
            + "fill-color: #777;"
            + "z-index: 1;"
        + "}"
        + "edge {"
            + "shape: line;"
            + "fill-color: #222;"
            + "arrow-size: 6px, 4px;"
            + "z-index: 0;"
        + "}"
        + "node:clicked {"
            + "fill-color: red;"
        + "}"
        + "node:selected {"
            + "fill-color: red;"
        + "}"
        + "edge.selection {"
            + "fill-color: red;"
        + "}";
    
    
    public static final String styleSheet2 = 
        "graph {"
            +"canvas-color: black;"
            +"fill-mode: gradient-vertical;"
            +"fill-color: black, #004;"
            +"padding: 20px;"
        +"}"
        +"node {"
            +"shape: circle;"
            +"size-mode: dyn-size;"
            +"size: 10px;"
            +"fill-mode: gradient-radial;"
            +"fill-color: #FFFC, #FFF0;"
            +"stroke-mode: none;"
            +"shadow-mode: gradient-radial;"
            +"shadow-color: #FFF5, #FFF0;"
            +"shadow-width: 5px;"
            +"shadow-offset: 0px, 0px;"
        +"}"
        +"node:clicked {"
            +"fill-color: #F00A, #F000;"
        +"}"
        +"node:selected {"
            +"fill-color: #00FA, #00F0;"
        +"}"
        +"edge {"
            +"shape: L-square-line;"
            +"size: 1px;"
            +"fill-color: #FFF3;"
            +"fill-mode: plain;"
            +"arrow-shape: none;"
        +"}"
        +"sprite {"
            +"shape: circle;"
            +"fill-mode: gradient-radial;"
            +"fill-color: #FFF8, #FFF0;"
        +"}";
}
