package fr.irit.smac.amasrenderer.controller.graph;

public enum EStateGraph {
    SHIFT_DOWN, AT_EASE, READY_TO_DELETE, READY_TO_ADD, READY_TO_ADD_NODE, READY_TO_DELETE_NODE, CTRL_DOWN, BUTTON_ADD_EDGE, BUTTON_DELETE_EDGE, BUTTON_ADD_NODE, BUTTON_DELETE_NODE, SELECTED_NODE
}
