package fr.irit.smac.amasrenderer;

/**
 * All states of the graph and the graphButtons are in in this enumeration
 */
public enum EStateGraph {
    AT_EASE, SHIFT_DOWN, CTRL_DOWN, READY_TO_DELETE_EDGE_TARGET, READY_TO_ADD_EDGE_TARGET, BUTTON_ADD_EDGE, BUTTON_DELETE_EDGE, BUTTON_ADD_NODE, BUTTON_DELETE_NODE, SELECTED_NODE, RESET_VIEW, AUTO_LAYOUT, FIRST_STEP, READY_TO_DELETE_EDGE_SOURCE, READY_TO_ADD_EDGE_SOURCE, READY_TO_ADD_NODE, READY_TO_DELETE_NODE
}
